-- Copyright 2016 Christopher F. Moran on behalf of PERRINN Limited.
--
-- Please refer to the file LICENSE in this repository

-- INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES();

INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Afghanistan','AFG',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Aland Islands','ALA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Albania','ALB',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Algeria','DZA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('American Samoa','ASM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Andorra','AND',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Angola','AGO',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Anguilla','AIA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Antarctica','ATA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Antigua and Barbuda','ATG',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Argentina','ARG',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Armenia','ARM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Aruba','ABW',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Australia','AUS',1,'State');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='AUS'),'New South Wales','NSW');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='AUS'),'Victoria','Vic');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='AUS'),'Tasmania','Tas');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='AUS'),'South Australia','SA');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='AUS'),'Western Australia','WA');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='AUS'),'Northern Territory','NT');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='AUS'),'Queensland','Qld');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='AUS'),'Australian Capital Territory','ACT');
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Austria','AUT',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Azerbaijan','AZE',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Bahamas','BHS',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Bahrain','BHR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Bangladesh','BGD',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Barbados','BRB',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Belarus','BLR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Belgium','BEL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Belize','BLZ',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Benin','BEN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Bermuda','BMU',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Bhutan','BTN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Bolivia','	BOL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Bosnia and Herzegovina','BIH',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Botswana','BWA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Bouvet Island','BVT',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Brazil','BRA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('British Virgin Islands','VGB',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('British Indian Ocean Territory','IOT',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Brunei Darussalam','BRN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Bulgaria','BGR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Burkina Faso','BFA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Burundi','BDI',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Cambodia','KHM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Cameroon','CMR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Canada','CAN',1,'Province');
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Cape Verde','CPV',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Cayman Islands','CYM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Central African Republic','CAF',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Chad','TCD',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Chile','CHL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('China','CHN',1,'Province');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Beijing','BJ');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Tianjin','TJ');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Hebei','HE');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Shanxi','SX');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Inner Mongolia','NM');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Liaoning','LN');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Jilin','JL');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Heilongjiang','HL');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Shanghai','SH');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Jiangsu','JS');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Zehjiang','ZJ');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Anhui','AH');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Fujian','FJ');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Jiangxi','JX');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Shandong','SD');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Henan','HA');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Hubei','HB');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Hunan','HN');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Guangdong','GD');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Guangxi','GX');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Hainan','HI');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Chongqing','CQ');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Sichuan','SC');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Guizhou','GZ');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Yunnan','YN');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Tibet','XZ');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Shaanxi','SN');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Gansu','GS');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Qinghai','QH');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Ningxia','NX');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Xinjiang','XJ');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Hong Kong SAR','HK');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Macau SAR','MC');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='CHN'),'Taiwan','TW');
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Hong Kong','HKG',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Macao','MAC',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Christmas Island','CXR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Cocos (Keeling) Islands','CCK',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Colombia','COL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Comoros','COM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Congo (Brazzaville)','COG',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Congo, Democratic Republic of the','COD',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Cook Islands','COK',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Costa Rica','CRI',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Côte d''Ivoire','CIV',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Croatia','HRV',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Cuba','CUB',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Cyprus','CYP',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Czech Republic','CZE',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Denmark','DNK',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Djibouti','DJI',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Dominica','DMA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Dominican Republic','DOM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Ecuador','ECU',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Egypt','EGY',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('El Salvador','SLV',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Equatorial Guinea','GNQ',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Eritrea','ERI',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Estonia','EST',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Ethiopia','ETH',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Falkland Islands (Malvinas)','FLK',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Faroe Islands','FRO',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Fiji','FJI',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Finland','FIN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('France','FRA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('French Guiana','GUF',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('French Polynesia','PYF',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('French Southern Territories','ATF',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Gabon','GAB',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Gambia','GMB',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Georgia','GEO',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Germany','DEU',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Ghana','GHA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Gibraltar','GIB',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Greece','GRC',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Greenland','GRL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Grenada','GRD',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Guadeloupe','GLP',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Guam','GUM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Guatemala','GTM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Guernsey','GGY',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Guinea','GIN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Guinea-Bissau','GNB',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Guyana','GUY',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Haiti','HTI',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Heard Island and Mcdonald Islands','HMD',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Holy See (Vatican City State)','VAT',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Honduras','HND',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Hungary','HUN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Iceland','ISL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('India','IND',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Indonesia','IDN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Iran, Islamic Republic of','IRN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Iraq','IRQ',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Ireland','IRL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Isle of Man','IMN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Israel','ISR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Italy','ITA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Jamaica','JAM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Japan','JPN',1,'Prefecture');
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Jersey','JEY',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Jordan','JOR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Kazakhstan','KAZ',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Kenya','KEN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Kiribati','KIR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Korea, Democratic People''s Republic of','PRK',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Korea, Republic of','KOR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Kuwait','KWT',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Kyrgyzstan','KGZ',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Lao PDR','AO',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Latvia','LVA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Lebanon','LBN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Lesotho','LSO',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Liberia','LBR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Libya','LBY',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Liechtenstein','LIE',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Lithuania','LTU',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Luxembourg','LUX',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Macedonia, Republic of','MKD',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Madagascar','MDG',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Malawi','MWI',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Malaysia','MYS',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Maldives','MDV',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Mali','MLI',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Malta','MLT',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Marshall Islands','MHL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Martinique','MTQ',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Mauritania','MRT',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Mauritius','MUS',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Mayotte','MYT',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Mexico','MEX',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Micronesia, Federated States of','FSM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Moldova','MDA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Monaco','MCO',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Mongolia','MNG',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Montenegro','MNE',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Montserrat','MSR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Morocco','MAR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Mozambique','MOZ',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Myanmar','MMR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Namibia','NAM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Nauru','NRU',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Nepal','NPL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Netherlands','NLD',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Netherlands Antilles','ANT',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('New Caledonia','NCL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('New Zealand','NZL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Nicaragua','NIC',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Niger','NER',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Nigeria','NGA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Niue','NIU',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Norfolk Island','NFK',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Northern Mariana Islands','MNP',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Norway','NOR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Oman','OMN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Pakistan','PAK',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Palau','PLW',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Palestinian Territory, Occupied','PSE',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Panama','PAN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Papua New Guinea','PNG',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Paraguay','PRY',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Peru','PER',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Philippines','PHL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Pitcairn','PCN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Poland','POL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Portugal','PRT',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Puerto Rico','PRI',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Qatar','QAT',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Réunion','REU',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Romania','ROU',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Russian Federation','RUS',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Rwanda','RWA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Saint-Barthélemy','BLM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Saint Helena','SHN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Saint Kitts and Nevis','KNA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Saint Lucia','LCA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Saint-Martin (French part)','MAF',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Saint Pierre and Miquelon','SPM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Saint Vincent and Grenadines','VCT',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Samoa','WSM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('San Marino','SMR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Sao Tome and Principe','STP',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Saudi Arabia','SAU',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Senegal','SEN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Serbia','SRB',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Seychelles','SYC',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Sierra Leone','SLE',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Singapore','SGP',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Slovakia','SVK',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Slovenia','SVN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Solomon Islands','SLB',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Somalia','SOM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('South Africa','ZAF',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('South Georgia and the South Sandwich Islands','SGS',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('South Sudan','SSD',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Spain','ESP',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Sri Lanka','LKA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Sudan','SDN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Suriname','SUR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Svalbard and Jan Mayen Islands','SJM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Swaziland','SWZ',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Sweden','SWE',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Switzerland','CHE',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Syria','SYR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Taiwan','TWN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Tajikistan','TJK',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Tanzania','TZA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Thailand','THA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Timor-Leste','TLS',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Togo','TGO',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Tokelau','TKL',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Tonga','TON',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Trinidad and Tobago','TTO',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Tunisia','TUN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Turkey','TUR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Turkmenistan','TKM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Turks and Caicos Islands','TCA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Tuvalu','TUV',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Uganda','UGA',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Ukraine','UKR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('United Arab Emirates','ARE',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('United Kingdom','GBR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('United States of America','USA',1,'State');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='USA'),'Alabama','AL');
INSERT INTO perrapp.region(country, region_name, region_code) VALUES((SELECT id FROM perrapp.country WHERE country_code='USA'),'Alaska','AK');
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('United States Minor Outlying Islands','UMI',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Uruguay','URY',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Uzbekistan','UZB',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Vanuatu','VUT',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Venezuela','VEN',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Viet Nam','VNM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Virgin Islands, US','VIR',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Wallis and Futuna Islands','WLF',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Western Sahara','ESH',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Yemen','YEM',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Zambia','ZMB',0,NULL);
INSERT INTO perrapp.country(country_name, country_code, has_division, division_name) VALUES('Zimbabwe','ZWE',0,NULL);
